### ISSUE TITLE
speed-test snap error TypeError: Cannot read property 'settings' of null

### ISSUE THREAD

**Issue by millengustavo** [bartaz/speed-test-snap#1]
I installed speed-test from a snap today, and when I attempt to run it on terminal it returns:

```
  Ping ⠦
```

  Download
    Upload
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'settings' of null
    at gotServers (/snap/speed-test/1/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:522:20)
    at /snap/speed-test/1/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:48:16
    at /snap/speed-test/1/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:238:7
    at Parser.<anonymous> (/snap/speed-test/1/lib/node_modules/speed-test/node_modules/speedtest-net/node_modules/xml2js/lib/xml2js.js:484:18)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Parser.exports.Parser.Parser.parseString (/snap/speed-test/1/lib/node_modules/speed-test/node_modules/speedtest-net/node_modules/xml2js/lib/xml2js.js:494:16)
    at Parser.parseString (/snap/speed-test/1/lib/node_modules/speed-test/node_modules/speedtest-net/node_modules/xml2js/lib/xml2js.js:7:59)
    at exports.parseString (/snap/speed-test/1/lib/node_modules/speed-test/node_modules/speedtest-net/node_modules/xml2js/lib/xml2js.js:535:19)
    at /snap/speed-test/1/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:236:5

**Comment by bartaz** [comment]
Thanks for reporting.

It seems to be an issue with underlying library that connects to speed-test.net servers.
It was already reported there: https://github.com/sindresorhus/speed-test/issues/36

I'll update the snap once it's fixed.

**Comment by bartaz** [comment]
@gustavopadre Turns out issue was already fixed (https://github.com/ddsol/speedtest.net/issues/25), so I repackaged the snap with updated libraries.

It should work fine after the update.

Thanks for the report!
